almny/Areas/Admin/Controllers/BookController.cs
using almny.Areas.Admin.Models;
using almny.Areas.Admin.Models.DTO;
using almny.Models;
using almny.Repositories.Abstract;
using almny.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace almny.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin/[controller]/[action]")]
    [Authorize(Roles = "admin")]
    public class BookController : Controller
    {
        private readonly IBaseRepository<Book> _bookRepository;
        private readonly DatabaseContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BookController(IBaseRepository<Book> bookRepository, DatabaseContext context, IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index(int? LevelId, int? DepartmentId,int? SemesterId, int? SubjectId)
        {
            List<Book> books = _bookRepository
                .GetAll()
                .Include(b => b.Department)
                .Include(b => b.Level)
                .Include(b => b.Semester)
                .Include(b => b.Subject)
                .Where(b =>
        (!LevelId.HasValue || b.LevelId == LevelId) &&
        (!DepartmentId.HasValue || b.DepartmentId == DepartmentId) &&
        (!SemesterId.HasValue || b.SemesterId == SemesterId) &&
        (!SubjectId.HasValue || b.SubjectId == SubjectId))
    .ToList();

            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(books);
        }

        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(BookViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    if (!string.IsNullOrEmpty(model.thumb))
                    {
                        string oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", model.thumb);
                        string oldBookPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/books", model.book);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                            System.IO.File.Delete(oldBookPath);
                        }
                    }

                    string imageName = Guid.NewGuid().ToString() + Path.GetExtension(files[0].FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", imageName);
                    string bookName = Guid.NewGuid().ToString() + Path.GetExtension(files[1].FileName);
                    string bookPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/books", bookName);

                    using (var fileStream = new FileStream(imagePath, FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    using (var fileStream = new FileStream(bookPath, FileMode.Create))
                    {
                        files[1].CopyTo(fileStream);
                    }

                    model.thumb = imageName;
                    model.book = bookName;
                }
                var book = new Book
                {
                    // تعيين الخصائص بناءً على الموديل
                    Title = model.Title,
                    book = model.book,
                    thumb = model.thumb,
                    SubjectId = model.SubjectId,
                    LevelId = model.LevelId,
                    DepartmentId = model.DepartmentId,
                    SemesterId = model.SemesterId,
                };

                // قم بإنشاء الموضوع باستخدام المخزن
                bool created = _bookRepository.Create(book);

                if (created)
                {
                    // يمكنك توجيه المستخدم إلى صفحة نجاح أو فعل آخر بناءً على الحاجة
                    return RedirectToAction("Index");
                }
                else
                {
                    // إذا فشلت العملية، يمكنك إعادة عرض النموذج مع رسالة خطأ
                    ModelState.AddModelError(string.Empty, "فشل في إنشاء الموضوع.");
                    ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
                    ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
                    ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
                    ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
                    return View(model);
                }
            }

            ModelState.AddModelError(string.Empty, "الرجاء ادخال كافة العناصر المطلوبة");
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var book = _bookRepository.FindByid(id);

            if (book == null)
            {
                return RedirectToAction("Index");
            }

            var model = new BookViewModel
            {
                // قم بتعيين الخصائص بناءً على الكائن
                Id = book.Id,
                Title = book.Title,
                book = book.book,
                thumb = book.thumb,
                SubjectId = book.SubjectId,
                LevelId = book.LevelId,
                DepartmentId = book.DepartmentId,
                SemesterId = book.SemesterId
            };

            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(BookViewModel model, int id)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    if (!string.IsNullOrEmpty(model.thumb))
                    {
                        string oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", model.thumb);
                        string oldBookPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/books", model.book);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                            System.IO.File.Delete(oldBookPath);
                        }
                    }

                    string imageName = Guid.NewGuid().ToString() + Path.GetExtension(files[0].FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", imageName);
                    string bookName = Guid.NewGuid().ToString() + Path.GetExtension(files[1].FileName);
                    string bookPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/books", bookName);

                    using (var fileStream = new FileStream(imagePath, FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    using (var fileStream = new FileStream(bookPath, FileMode.Create))
                    {
                        files[1].CopyTo(fileStream);
                    }

                    model.thumb = imageName;
                    model.book = bookName;
                }

                // استرجاع كائن الكتاب الحالي من المستودع
                var existingbook = _bookRepository.FindByid(id);

                if (existingbook == null)
                {
                    // إذا لم يتم العثور على الكتاب، قم بإعادة توجيه المستخدم إلى صفحة خطأ أو صفحة الفهرس أو أي صفحة أخرى
                    return RedirectToAction("Index");
                }

                // تحديث كائن الكتاب الحالي بقيم من نموذج العرض
                existingbook.Title = model.Title;
                existingbook.book = model.book;
                existingbook.thumb = model.thumb;
                existingbook.SubjectId = model.SubjectId;
                existingbook.LevelId = model.LevelId;
                existingbook.DepartmentId = model.DepartmentId;
                existingbook.SemesterId = model.SemesterId;

                // استدعاء طريقة التحديث في المستودع لحفظ التغييرات
                bool updated = _bookRepository.Update(existingbook);

                if (updated)

almny/Areas/Admin/Controllers/SubjectController.cs
using almny.Areas.Admin.Models.DTO;
using almny.Models;
using almny.Repositories.Abstract;
using almny.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace almny.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin/[controller]")]
    [Authorize(Roles = "admin")]
    public class SubjectController : Controller
    {
        private readonly IBaseRepository<Subject> _subjectRepository;

        public SubjectController(IBaseRepository<Subject> subjectRepository)
        {
            _subjectRepository = subjectRepository;
        }

        [HttpGet("[action]")]
        public IActionResult Index()
        {
            // قم بالحصول على جميع المواضيع باستخدام المخزن
            var subjects = _subjectRepository.GetAll().ToList();

            // قم بتمرير البيانات إلى العرض
            return View(subjects);
        }

        [HttpGet("[action]")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("[action]")]
        public IActionResult Create(SubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                // قم بتحويل SubjectViewModel إلى كائن Subject
                var subject = new Subject
                {
                    // تعيين الخصائص بناءً على الموديل
                    // على سبيل المثال، افترض أن SubjectViewModel لديها خاصية SubjectName
                    Name = model.Name
                };

                // قم بإنشاء الموضوع باستخدام المخزن
                bool created = _subjectRepository.Create(subject);

                if (created)
                {
                    // يمكنك توجيه المستخدم إلى صفحة نجاح أو فعل آخر بناءً على الحاجة
                    return RedirectToAction("Index");
                }
                else
                {
                    // إذا فشلت العملية، يمكنك إعادة عرض النموذج مع رسالة خطأ
                    ModelState.AddModelError(string.Empty, "فشل في إنشاء الموضوع.");
                    return View(model);
                }
            }

            // إذا كان هناك أخطاء في نموذج الإدخال، قم بإعادة عرض النموذج
            return View(model);
        }

        [HttpGet("[action]")]
        public IActionResult Edit(int id)
        {
            // قم بالبحث عن الكائن المطلوب باستخدام المعرف
            var subject = _subjectRepository.FindByid(id);

            if (subject == null)
            {
                // إذا لم يتم العثور على الكائن، قم بإعادة توجيه المستخدم إلى صفحة خطأ أو صفحة الفهرس أو أي صفحة أخرى
                return RedirectToAction("Index");
            }

            // قم بتحويل الكائن إلى نموذج التحرير (SubjectViewModel) إذا كان ذلك ضروريًا
            var model = new SubjectViewModel
            {
                // قم بتعيين الخصائص بناءً على الكائن
                // على سبيل المثال، افترض أن SubjectViewModel لديها خاصية SubjectName
                Id = subject.Id,
                Name = subject.Name
            };

            // قم بإعادة عرض نموذج التحرير مع البيانات المحملة
            return View(model);
        }

        [HttpPost("[action]")]
        public IActionResult Edit(SubjectViewModel model,int id)
        {
            if (ModelState.IsValid)
            {
                // قم بالبحث عن الكائن المطلوب باستخدام المعرف
                var existingSubject = _subjectRepository.FindByid(model.Id);

                if (existingSubject == null)
                {
                    // إذا لم يتم العثور على الكائن، قم بإعادة توجيه المستخدم إلى صفحة خطأ أو صفحة الفهرس أو أي صفحة أخرى
                    return RedirectToAction("Index");
                }

                // تحديث الخصائص بناءً على نموذج التحرير
                // على سبيل المثال، افترض أن SubjectViewModel لديها خاصية SubjectName
                existingSubject.Name = model.Name;

                // قم بتحديث الكائن باستخدام المخزن
                bool updated = _subjectRepository.Update(existingSubject);

                if (updated)
                {
                    // في حال نجاح التحديث، قم بتوجيه المستخدم إلى صفحة الفهرس أو أي صفحة أخرى
                    return RedirectToAction("Index");
                }
                else
                {
                    // إذا فشل التحديث، قم بإعادة عرض نموذج التحرير مع رسالة خطأ
                    ModelState.AddModelError(string.Empty, "فشل في تحديث الموضوع.");
                    return View(model);
                }
            }

            // إذا كان هناك أخطاء في نموذج التحرير، قم بإعادة عرض النموذج مع الأخطاء
            return View(model);
        }

        [HttpGet("[action]")]
        public IActionResult Delete(int id)
        {
            var entityToDelete = _subjectRepository.FindByid(id);

            if (entityToDelete != null)
            {
                bool deleted = _subjectRepository.Delete(entityToDelete);

                if (deleted)
                {
                    // في حال نجاح الحذف، يمكنك توجيه المستخدم إلى صفحة الفهرس أو أي صفحة أخرى
                    return RedirectToAction("Index");
                }
            }

            // في حالة فشل الحذف، يمكنك إرجاع رسالة خطأ أو توجيه المستخدم إلى صفحة الفهرس أو أي صفحة أخرى
            return RedirectToAction("Index");
        }


    }
}

almny/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using almny.Models;
@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

    @{
    var userImage = ((await userManager.GetUserAsync(User)).ProfilePicture);
    var userName = ((await userManager.GetUserAsync(User)).Name);
    var userid= ((await userManager.GetUserAsync(User)).Id);

    }
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/Admin/Images/icon/3almny.png" />
    <!-- Main Template CSS File -->
    <link href="~/Admin/css/admin_style.css" rel="stylesheet" />
    <!-- Render All Elements Normally -->
    <link href="~/Admin/css/normalize.css" rel="stylesheet" />
    <!-- Font Awesome Library -->
    <link href="~/Admin/css/all.min.css" rel="stylesheet" />
    <style>
        .text-danger {
            font-size: 1rem;
            color: white;
            margin: 1rem;
            margin: 10px auto;
            color: #D8000C;
            background-color: #FFBABA;
            font-size: 1.5rem;
        }
    </style>
</head>
<body>
    <!-- Start Header Section -->
    <header class="header">

        <section class="flex">

            <a asp-action="Index" asp-controller="Dashboard" class="logo">المشرف.</a>

            <div class="icons">
                <div id="menu-btn" class="fas fa-bars"></div>
                <div id="user-btn" class="fas fa-user"></div>
                <div id="toggle-btn" class="fas fa-sun"></div>
                <a target="_blank" asp-area="" asp-action="Index" asp-controller="Home">
                    <div id="view-website" class="fas fa-desktop"></div>
                </a>
            </div>

            <div class="profile">
                @if(userImage == null)
                {
                <img src="~/Images/img/pic.jpg" class="image" alt="">

                }
                else
                {
                <img src="~/Uploads/images/@userImage" class="image" alt="">

                }                
                <h3>@userName</h3>
                <a asp-action="Update" asp-controller="Account" asp-route-id="@userid" class="btn">تحديث الملف الشخصي</a>
                <a asp-action="Logout" asp-controller="Account" class="delete-btn">تسجيل خروج</a>
            </div>
        </section>

    </header>
    <!-- End Header Section -->
    <!-- side bar section starts  -->
    <div class="side-bar">

        <div class="close-side-bar">
            <i class="fas fa-times"></i>
        </div>

        <div class="profile">
            @if(userImage == null)
            {
            <img src="~/Images/img/pic.jpg" class="image" alt="">

            }
            else
            {
            <img src="~/Uploads/images/@userImage" class="image" alt="">

            }
            <h3>@userName</h3>
            <a asp-action="Update" asp-controller="Account" asp-route-id="@userid" class="btn">تحديث الملف الشخصي</a>
        </div>
        <nav class="navbar">
            <a asp-action="Index" asp-controller="Dashboard"><i class="fas fa-home"></i><span>الصفحه الرئيسيه</span></a>
            <a asp-action="Index" asp-controller="Subject"><i class="fa-solid fa-bars-staggered"></i><span>المواد الدراسية</span></a>
            <a asp-action="Index" asp-controller="Video"><i class="fas fa-video"></i><span>الفديوهات التعليمية</span></a>
            <a asp-action="Index" asp-controller="Book"><i class="fas fa-book"></i><span>الكتب الدراسية</span></a>
            @* <a asp-action="Index" asp-controller="Exam"><i class="fa fa-quora"></i><span>الامتحانات السابقة</span></a> *@
            @* <a asp-action="Index" asp-controller="User"><i class="fas fa-user"></i><span>المستخدمين</span></a> *@
            <a asp-action="Logout" asp-controller="Account"><i class="fas fa-right-from-bracket"></i><span>تسجيل خروج</span></a>
        </nav>

    </div>
    <!-- side bar section ends -->

    <div>
        @RenderBody()
    </div>

    <footer class="footer">
        <p>&copy; @DateTime.Now.Year - بواسطة CodeGenius</p>
    </footer>
    <script src="~/Admin/js/admin_script.js"></script>
    @* <script src="~/js/modernizr-2.8.3.js"></script> *@
</body>
</html>