almny/Areas/Admin/Models/DTO/VideoViewModel.cs
using almny.Models;
using System.ComponentModel.DataAnnotations;

namespace almny.Areas.Admin.Models.DTO
{
    public class VideoViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "الرجاء ادخال عنوان الفيديو")]
        public string Title { get; set; }

        [Required(ErrorMessage = "الرجاء اختيار فيديو")]
        public string video { get; set; }

        [Required(ErrorMessage = "الرجاء اختيار صورة مصغرة")]
        public string thumb { get; set; }

        [Required(ErrorMessage = "الرجاء اختيار المستوى الدراسي")]
        public int LevelId { get; set; }

        [Required(ErrorMessage = "الرجاء اختيار القسم")]
        public int DepartmentId { get; set; }

        [Required(ErrorMessage = "الرجاء اختيار الفصل الدراسي")]
        public int SemesterId { get; set; }

        [Required(ErrorMessage = "الرجاء اختيار المادة الدراسي")]
        public int SubjectId { get; set; }

        public DateTime? date { get; set; }

        public virtual Subject? Subject { get; set; }
        public virtual Level? Level { get; set; }
        public virtual Department? Department { get; set; }
        public virtual Semester? Semester { get; set; }
    }
}

almny/Areas/Admin/Controllers/VideoController.cs
using almny.Areas.Admin.Models.DTO;
using almny.Models;
using almny.Repositories.Abstract;
using almny.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace almny.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin/[controller]/[action]")]
    [Authorize(Roles = "admin")]
    public class VideoController : Controller
    {
        private readonly IBaseRepository<Video> _videoRepository;
        private readonly DatabaseContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public VideoController(IBaseRepository<Video> videoRepository, DatabaseContext context, IWebHostEnvironment webHostEnvironment)
        {
            _videoRepository = videoRepository;
            _context = context;
            _webHostEnvironment = webHostEnvironment;

        }

        public IActionResult Index(int? LevelId, int? DepartmentId, int? SemesterId, int? SubjectId)
        {
            List<Video> videos = _videoRepository
                .GetAll()
                .Include(b => b.Department)
                .Include(b => b.Level)
                .Include(b => b.Semester)
                .Include(b => b.Subject)
                .Where(b =>
        (!LevelId.HasValue || b.LevelId == LevelId) &&
        (!DepartmentId.HasValue || b.DepartmentId == DepartmentId) &&
        (!SemesterId.HasValue || b.SemesterId == SemesterId) &&
        (!SubjectId.HasValue || b.SubjectId == SubjectId))
        .ToList();

            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(videos);
        }
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(VideoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    if (!string.IsNullOrEmpty(model.thumb))
                    {
                        string oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", model.thumb);
                        string oldVideoPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/videos", model.video);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                            System.IO.File.Delete(oldVideoPath);
                        }
                    }

                    string imageName = Guid.NewGuid().ToString() + Path.GetExtension(files[0].FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", imageName);
                    string videoName = Guid.NewGuid().ToString() + Path.GetExtension(files[1].FileName);
                    string videoPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/videos", videoName);

                    using (var fileStream = new FileStream(imagePath, FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    using (var fileStream = new FileStream(videoPath, FileMode.Create))
                    {
                        files[1].CopyTo(fileStream);
                    }

                    model.thumb = imageName;
                    model.video = videoName;
                }
                var video = new Video
                {
                    // تعيين الخصائص بناءً على الموديل
                    Title = model.Title,
                    video = model.video,
                    thumb = model.thumb,
                    SubjectId = model.SubjectId,
                    LevelId = model.LevelId,
                    DepartmentId = model.DepartmentId,
                    SemesterId = model.SemesterId,
                    date = DateTime.Now
                };

                // قم بإنشاء الموضوع باستخدام المخزن
                bool created = _videoRepository.Create(video);

                if (created)
                {
                    // يمكنك توجيه المستخدم إلى صفحة نجاح أو فعل آخر بناءً على الحاجة
                    return RedirectToAction("Index");
                }
                else
                {
                    // إذا فشلت العملية، يمكنك إعادة عرض النموذج مع رسالة خطأ
                    ModelState.AddModelError(string.Empty, "فشل في إنشاء الموضوع.");
                    ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
                    ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
                    ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
                    ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
                    return View(model);
                }
            }

            ModelState.AddModelError(string.Empty, "الرجاء ادخال كافة العناصر المطلوبة");
            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var video = _videoRepository.FindByid(id);

            if (video == null)
            {
                // إذا لم يتم العثور على الكائن، قم بإعادة توجيه المستخدم إلى صفحة خطأ أو صفحة الفهرس أو أي صفحة أخرى
                return RedirectToAction("Index");
            }

            // قم بتحويل الكائن إلى نموذج التحرير (SubjectViewModel) إذا كان ذلك ضروريًا
            var model = new VideoViewModel
            {
                // قم بتعيين الخصائص بناءً على الكائن
                // على سبيل المثال، افترض أن SubjectViewModel لديها خاصية SubjectName
                Id = video.Id,
                Title = video.Title,
                video = video.video,
                thumb = video.thumb,
                SubjectId = video.SubjectId,
                LevelId = video.LevelId,
                DepartmentId = video.DepartmentId,
                SemesterId = video.SemesterId
            };

            ViewData["DepartmentId"] = new SelectList(_context.Departments, "Id", "Name");
            ViewData["LevelId"] = new SelectList(_context.Levels, "Id", "Name");
            ViewData["SemesterId"] = new SelectList(_context.Semesters, "Id", "Name");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(VideoViewModel model, int id)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    if (!string.IsNullOrEmpty(model.thumb))
                    {
                        string oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", model.thumb);
                        string oldVideoPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/videos", model.video);
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                            System.IO.File.Delete(oldVideoPath);
                        }
                    }

                    string imageName = Guid.NewGuid().ToString() + Path.GetExtension(files[0].FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/images", imageName);
                    string videoName = Guid.NewGuid().ToString() + Path.GetExtension(files[1].FileName);
                    string videoPath = Path.Combine(_webHostEnvironment.WebRootPath, "Uploads/videos", videoName);

                    using (var fileStream = new FileStream(imagePath, FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    using (var fileStream = new FileStream(videoPath, FileMode.Create))
                    {
                        files[1].CopyTo(fileStream);
                    }

                    model.thumb = imageName;
                    model.video = videoName;
                }

                // استرجاع كائن الفيديو الحالي من المستودع
                var existingVideo = _videoRepository.FindByid(id);

                if (existingVideo == null)
                {
                    // إذا لم يتم العثور على الفيديو، قم بإعادة توجيه المستخدم إلى صفحة خطأ أو صفحة الفهرس أو أي صفحة أخرى
                    return RedirectToAction("Index");
                }

                // تحديث كائن الفيديو الحالي بقيم من نموذج العرض
                existingVideo.Title = model.Title;
                existingVideo.video = model.video;
                existingVideo.thumb = model.thumb;
                existingVideo.SubjectId = model.SubjectId;
                existingVideo.LevelId = model.LevelId;

almny/Controllers/VideosController.cs
using almny.Models;
using almny.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace almny.Controllers
{
    [Authorize]
    public class VideosController : Controller
{

        private readonly DatabaseContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public VideosController(DatabaseContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
    {
        return View();
    }

        public async Task<IActionResult> Details(int id)
        {
            var userId = ((await _userManager.GetUserAsync(User)).Id);
            var video = _context.Videos.FirstOrDefault(x => x.Id == id);

            ViewData["UserId"] = userId;
            ViewData["IsLiked"] = IsLiked(userId, id);
            ViewData["UserLikesCount"] = _context.Likes.Count(u => u.VideoId == id);
            return View(video);
        }

        public bool IsLiked(string userId, int videoId)
        {
            bool IsLiked = false;
            var like = _context.Likes.FirstOrDefault(l => l.VideoId == videoId & l.UserId == userId);
            if (like != null)
            {
                IsLiked = true;
            }

            return IsLiked;
        }

    }
}

almny/Areas/Admin/Views/Video/Create.cshtml
@model almny.Areas.Admin.Models.DTO.VideoViewModel

@{
    ViewData["Title"] = "اضافة - الفيديوهات التعليمية";
}

<section class="video-form">

    <h1 class="heading">أضافة فيديو تعليمي</h1>

    <form asp-action="Create" asp-controller="Video" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <input asp-for="thumb" hidden />
        <input asp-for="video" hidden />
        <input asp-for="Id" hidden />
        <p>عنوان الفيديو <span>*</span></p>
        <input asp-for="Title" class="box" placeholder="ادخل عنوان الفيديو" maxlength="100" />
        <span asp-validation-for="Title" class="text-danger"></span>

        <p>المستوى الدراسي <span>*</span></p>
        <select asp-for="LevelId" asp-items="ViewBag.LevelId" class="box">
            <option value="">-- المستوى الدراسي</option>
        </select>
        <span asp-validation-for="LevelId" class="text-danger"></span>

        <p>القسم <span>*</span></p>
        <select asp-for="DepartmentId" asp-items="ViewBag.DepartmentId" class="box">
            <option value="">-- القسم</option>
        </select>
        <span asp-validation-for="DepartmentId" class="text-danger"></span>

        <p>الفصل الدراسي <span>*</span></p>
        <select asp-for="SemesterId" asp-items="ViewBag.SemesterId" class="box">
            <option value="">-- الفصل الدراسي</option>
        </select>
        <span asp-validation-for="SemesterId" class="text-danger"></span>

        <p>المادة الدراسية <span>*</span></p>
        <select asp-for="SubjectId" asp-items="ViewBag.SubjectId" class="box" class="box">
            <option value="">-- المادة الدراسية</option>
        </select>
        <span asp-validation-for="SubjectId" class="text-danger"></span>

        <p>اختر صورة مصغرة <span>*</span></p>
        <input type="file" name="thumb"  class="box" accept=".png, .jpg, .jpeg">
        <span asp-validation-for="thumb" class="text-danger"></span>

        <p>اختر فيديو <span>*</span></p>
        <input type="file" name="video" id="video" accept=".mp4"  class="box">
        <span asp-validation-for="video" class="text-danger"></span>
        <div id="errorMessage" class="text-danger"></div>

        <input type="submit" value="اضافة" name="submit" id="save" class="btn">
        <span asp-validation-summary="All" class="text-danger"></span>
    </form>
</section>

<script>
    $(document).ready(function () {
        $('#video').change(function () {
            var fileSize = this.files[0].size;
            var megabytes = fileSize / (1024 * 1024);
            if (megabytes > 100) {
                $('#errorMessage').text("حجم الفيديو أكبر من 100 ميجابايت");
            } else {
                $('#errorMessage').empty();
            }
        });
    });
</script>

almny/Areas/Admin/Views/Video/Edit.cshtml
@model almny.Areas.Admin.Models.DTO.VideoViewModel

@{
    ViewData["Title"] = "تعديل - الفيديوهات التعليمية";
}

<section class="video-form">

    <h1 class="heading">تعديل فيديو تعليمي</h1>

    <form asp-action="Edit" method="post" asp-route-id="@Model.Id" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <input asp-for="thumb" hidden />
        <input asp-for="video" hidden />
        <input asp-for="Id" hidden />

        <p>عنوان الفيديو <span>*</span></p>
        <input asp-for="Title" class="box" placeholder="ادخل عنوان الفيديو" maxlength="100" />
        <span asp-validation-for="Title" class="text-danger"></span>

        <p>المستوى الدراسي <span>*</span></p>
        <select asp-for="LevelId" asp-items="ViewBag.LevelId" class="box">
            <option value="">-- المستوى الدراسي</option>
        </select>
        <span asp-validation-for="LevelId" class="text-danger"></span>

        <p>القسم <span>*</span></p>
        <select asp-for="DepartmentId" asp-items="ViewBag.DepartmentId" class="box">
            <option value="">-- القسم</option>
        </select>
        <span asp-validation-for="DepartmentId" class="text-danger"></span>

        <p>الفصل الدراسي <span>*</span></p>
        <select asp-for="SemesterId" asp-items="ViewBag.SemesterId" class="box">
            <option value="">-- الفصل الدراسي</option>
        </select>
        <span asp-validation-for="SemesterId" class="text-danger"></span>

        <p>المادة الدراسية <span>*</span></p>
        <select asp-for="SubjectId" asp-items="ViewBag.SubjectId" class="box" class="box">
            <option value="">-- المادة الدراسية</option>
        </select>
        <span asp-validation-for="SubjectId" class="text-danger"></span>

        <p>اختر صورة مصغرة <span>*</span></p>
        <input type="file" name="thumb" class="box" accept=".png, .jpg, .jpeg">
        <span asp-validation-for="thumb" class="text-danger"></span>
        <div><img src="~/Uploads/images/@Model.thumb" /></div>


        <p>اختر فيديو <span>*</span></p>
        <input type="file" name="video" id="video" accept=".mp4" class="box">
        <span asp-validation-for="video" class="text-danger"></span>
        <div>
            <video src="~/Uploads/videos/@Model.video"
                   controls
                   poster="~/Uploads/images/@Model.thumb"
                   id="video">
            </video>
        </div>

        <div id="errorMessage" class="text-danger"></div>

        <input type="submit" value="حفظ" name="submit" class="btn">
        <span asp-validation-summary="All" class="text-danger"></span>
    </form>
</section>

<script>
    $(document).ready(function () {
        $('#video').change(function () {
            var fileSize = this.files[0].size;
            var megabytes = fileSize / (1024 * 1024);
            if (megabytes > 100) {
                $('#errorMessage').text("حجم الفيديو أكبر من 100 ميجابايت");
            } else {
                $('#errorMessage').empty();
            }
        });
    });
</script>

almny/Areas/Admin/Views/Video/Index.cshtml
@model IEnumerable<almny.Models.Video>

@{
    ViewData["Title"] = "الفيديوهات التعليمية";
}

<div class="table">
    <div class="table_header">
        <h1 class="title">الفيديوهات التعليمية</h1>
        <div>
            <a class="btn" asp-action="Create">أضافة جديدة</a>
        </div>
    </div>
    <form method="get" asp-action="Index" class="form-row">
        <p>المستوى الدراسي</p>
        <select name="LevelId" asp-items="ViewBag.LevelId" class="box">
            <option value="">-- المستوى الدراسي</option>
        </select>
        <p>القسم</p>
        <select name="DepartmentId" asp-items="ViewBag.DepartmentId" class="box">
            <option value="">-- القسم</option>
        </select>

        <p>الفصل الدراسي</p>
        <select name="SemesterId" asp-items="ViewBag.SemesterId" class="box">
            <option value="">-- الفصل الدراسي</option>
        </select>

        <p>المادة الدراسية</p>
        <select name="SubjectId" asp-items="ViewBag.SubjectId" class="box" class="box">
            <option value="">-- المادة الدراسية</option>
        </select>

        <button class="btn" type="submit">تحديث</button>

    </form>

    <div class="table-section">
        <table>
            <thead>
                <tr>
                    <th>#م</th>
                    <th>عنوان الفيديو</th>
                    <th>الصورة</th>
                    <th>المادة</th>
                    <th>المستوى الدراسي</th>
                    <th>القسم</th>
                    <th>الفصل الدراسي</th>
                    <th> اعداد</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            <img src="~/Uploads/images/@item.thumb">
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subject.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Level.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Department.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Semester.Name)
                        </td>
                        <td>
                            <a  asp-action="Edit" asp-route-id="@item.Id" class="btn-edit"><i class="fas fa-edit"></i></a>
                            <a onclick="return confirm('هل انت متاكد من حذف هذه الفيديو؟');"  asp-action="Delete" asp-route-id="@item.Id" class="btn-delete"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>